/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.MainController;
import Models.UserModel;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JColorChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Miguel Roa
 */
public class CreacionUsuarioView extends javax.swing.JPanel {
    
    MainController mainController;
    JOptionPane pane;
    Boolean esProfesor;

    /**
     * Crea una CreacionUsuarioView
     * @param mainController
     */
    public CreacionUsuarioView(MainController mainController) {
        initComponents();
        
        this.mainController = mainController;
        
        this.btnOK.setBackground(Color.decode("#7A91FF"));
               
        this.labelLoading.setVisible(false);  
        
        this.esProfesor = false;
    }
    
    //Set y get
    public MainController getMainController() {
        return mainController;
    }

    public void setMainController(MainController mainController) {
        this.mainController = mainController;
    }

    public JOptionPane getPane() {
        return pane;
    }

    public void setPane(JOptionPane pane) {
        this.pane = pane;
    }

    public JButton getBtnOK() {
        return btnOK;
    }

    public void setBtnOK(JButton btnOK) {
        this.btnOK = btnOK;
    }

    public JColorChooser getColorPicker() {
        return colorPicker;
    }

    public void setColorPicker(JColorChooser colorPicker) {
        this.colorPicker = colorPicker;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JTextField getTxtApellido() {
        return txtApellido;
    }

    public void setTxtApellido(JTextField txtApellido) {
        this.txtApellido = txtApellido;
    }

    public JTextField getTxtNombre() {
        return txtNombre;
    }

    public void setTxtNombre(JTextField txtNombre) {
        this.txtNombre = txtNombre;
    }

    public Boolean getEsProfesor() {
        return esProfesor;
    }

    public void setEsProfesor(Boolean esProfesor) {
        this.esProfesor = esProfesor;
    }

    public JCheckBox getCheckEsProfesor() {
        return CheckEsProfesor;
    }

    public void setCheckEsProfesor(JCheckBox CheckEsProfesor) {
        this.CheckEsProfesor = CheckEsProfesor;
    }  

    public JLabel getLabelLoading() {
        return labelLoading;
    }

    public void setLabelLoading(JLabel labelLoading) {
        this.labelLoading = labelLoading;
    }
    
    
    /*
    * Permite entrar en la ventana de chat
    */
    public void mostrarChat(){
        try{     
            
            UserModel usuario = new UserModel(
                this.txtNombre.getText()
                , this.txtApellido.getText()
                , this.colorPicker.getColor()
            );
            
            mainController.mostrarChat(usuario, esProfesor, this, this.colorPicker.getColor());           
            
        }catch(Exception error){
            System.out.println("Existe un error para abrir la ventana de chat con el user indicado: " + error.toString());
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        colorPicker = new javax.swing.JColorChooser();
        btnOK = new javax.swing.JButton();
        CheckEsProfesor = new javax.swing.JCheckBox();
        labelLoading = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Crea un usuario"));
        setMaximumSize(new java.awt.Dimension(550, 460));
        setMinimumSize(new java.awt.Dimension(550, 460));
        setPreferredSize(new java.awt.Dimension(550, 460));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Nombre:");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                none(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Apelllido");

        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApellidoKeyReleased(evt);
            }
        });

        colorPicker.setBorder(javax.swing.BorderFactory.createTitledBorder("Elige un color"));
        colorPicker.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                colorPickerKeyReleased(evt);
            }
        });

        btnOK.setBackground(new java.awt.Color(153, 153, 153));
        btnOK.setForeground(new java.awt.Color(255, 255, 255));
        btnOK.setText("OK!");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        CheckEsProfesor.setText("¿Es usted el profesor?");
        CheckEsProfesor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CheckEsProfesorItemStateChanged(evt);
            }
        });

        labelLoading.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelLoading.setForeground(new java.awt.Color(102, 51, 255));
        labelLoading.setText("loading");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CheckEsProfesor)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(colorPicker, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 9, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2)
                                    .addComponent(txtApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                    .addComponent(labelLoading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(79, 79, 79)
                                .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(15, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtApellido, txtNombre});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApellido)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CheckEsProfesor)
                    .addComponent(labelLoading, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(colorPicker, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        mostrarChat();
    }//GEN-LAST:event_btnOKActionPerformed

    private void none(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_none
        //ERROR
    }//GEN-LAST:event_none

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            try{
                mostrarChat();
            }catch(Exception error){
                System.out.println("Existe un error para enviar el mensaje en cuestión: " + error.toString());
            }           
        }
    }//GEN-LAST:event_txtNombreKeyReleased

    private void txtApellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            try{
                mostrarChat();
            }catch(Exception error){
                System.out.println("Existe un error para enviar el mensaje en cuestión: " + error.toString());
            }           
        }
    }//GEN-LAST:event_txtApellidoKeyReleased

    private void colorPickerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_colorPickerKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            try{
                mostrarChat();
            }catch(Exception error){
                System.out.println("Existe un error para enviar el mensaje en cuestión: " + error.toString());
            }           
        }
    }//GEN-LAST:event_colorPickerKeyReleased

    private void CheckEsProfesorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CheckEsProfesorItemStateChanged
        //Si cambia el checkbox para saber si es profesor o no
        if(this.CheckEsProfesor.isSelected()){
            this.esProfesor = true;
        }else{
            this.esProfesor = false;
        }
    }//GEN-LAST:event_CheckEsProfesorItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckEsProfesor;
    private javax.swing.JButton btnOK;
    private javax.swing.JColorChooser colorPicker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelLoading;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables


}
